server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/web_nwafu?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
file-service:
  path: /data/docker/nginx/html/images/
  image-url: http://59.110.24.11/images/