server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_nwafu?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: windlinxy@0014YST
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file-service:
  path: D:\Nginx\nginx-1.20.2\html\images\
  image-url: http://localhost:8081/images/