spring:
  jmx:
    enabled: off

  main:
    lazy-initialization: off
    banner-mode: off

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  datasource:
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 1200000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false


mybatis-plus:
  global-config:
    banner: false
  type-enums-package: pers.nwafumaster.enums

management:
  server:
    port: 8086

  endpoints:
    web:
      base-path: /ops
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
jwt:
  secret: NWAFU
  expire-time: 604800

# debug: on 自动配置查看