spring:
#  profiles:
#    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 1200000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
mybatis-plus:
  global-config:
    banner: false
  type-enums-package: pers.nwafumaster.enums

management:
  endpoint:
    shutdown:
      enabled: true
    beans:
      enabled: true
    health:
      enabled: true

  server:
    address: localhost
    port: 8086

  endpoints:
    web:
      base-path: /ops
      path-mapping:
        shutdown: shutdown
        health: health
        beans: beans
      exposure:
        include: shutdown,health,beans
jwt:
  key: NWAFU